project:
  type: website
  preview:
    port: 3000

website:
  title: "Deven Mistry"
  site-url: https://deven367.github.io/
  google-analytics: G-W16WSWL8WW
  navbar:
    right:
      - about.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "TIL"
        file: til.qmd
      - icon: github
        href: https://github.com/deven367/
      - icon: twitter
        href: https://twitter.com/deven367
  favicon: favicon.png

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



